package com.munishgarg.microsecurity.book1.ch5_edge_observability;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

@Component
public class AuditFilter extends OncePerRequestFilter {

    private static final Logger log = LoggerFactory.getLogger(AuditFilter.class);

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
            throws ServletException, IOException {

        // 1. Extract existing Trace ID from the Gateway, or generate a new one if this is the start of the chain.
        String traceId = request.getHeader("X-Trace-Id");
        if (traceId == null || traceId.isBlank()) {
            traceId = UUID.randomUUID().toString();
        }

        // 2. Extract Client IP
        String clientIp = request.getRemoteAddr();
        String forwardedFor = request.getHeader("X-Forwarded-For");
        if (forwardedFor != null && !forwardedFor.isBlank()) {
            clientIp = forwardedFor.split(",")[0].trim();
        }

        // 3. Populate Spring/SLF4J Mapped Diagnostic Context (MDC)
        // This makes 'traceId' and 'clientIp' available to the 'logging.pattern' defined in application.yml
        // for EVERY log statement executed on this thread.
        MDC.put("traceId", traceId);
        MDC.put("clientIp", clientIp);

        long startTime = System.currentTimeMillis();
        
        try {
            log.info("Incoming Request: {} {}", request.getMethod(), request.getRequestURI());
            
            // Add the trace ID to the response header so the client can reference it in bug reports
            response.addHeader("X-Trace-Id", traceId);
            
            filterChain.doFilter(request, response);
            
        } finally {
            long duration = System.currentTimeMillis() - startTime;
            log.info("Outgoing Response: {} - Took {}ms", response.getStatus(), duration);
            
            // CRITICAL SECURITY MEASURE:
            // Threads in application servers are pooled and reused.
            // If we do not clear the MDC, the traceId and IP of THIS user might 
            // leak into logs generated by the NEXT user utilizing this same thread.
            MDC.clear();
        }
    }
}
